name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_REPO }} .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_REPO }}

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Create private key file
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 -d > key.pem
          chmod 400 key.pem

      - name: Copy .env to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem .env ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/app.env

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_REPO }}
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 80:8000 --env-file app.env ${{ secrets.DOCKER_REPO }}
          EOF
